Resetting pr
arumoy-shome/UWNerdist pull request #49
Opened 2017-07-31 18:01 UTC by vishalbabu

Resetting previous changes to CONTRIBUTING.md so a proper merge can occur.

2017-07-31 22:40 UTC, arumoy-shome commented
Nice! Can you address the changes I had requested in #35?

2017-08-03 02:22 UTC, arumoy-shome commented
@vishalbabu I think you forgot to include the new FAQ doc that contains your note in the PR? Can you push it up so we can 🚀 this PR?

2017-08-15 21:02 UTC, arumoy-shome commented
Looking good, however there is nothing that links to the new doc that you just created. We should try to make it easier for others to find it, I suggest we add a link to the FAQ doc on the main README file. It should probably be somewhere in the setup section.

Since the doc is markdown you can style it, I have left some comments. Come to think of it, I don't think I have any guidelines on how to write docs so perhaps we should add that? @vishalbabu would you mind opening up an issue for it? We can discuss and develop the guide in the issue once you open it. 😄

2017-08-15 21:06 UTC, arumoy-shome requested changes
A few styling changes are required before we can merge this. Looks good otherwise!

2017-08-15 21:06 UTC, arumoy-shome commented on docs/FAQs.md
> +Frequently Asked Questions
This should be a level 1 header.

2017-08-15 21:06 UTC, arumoy-shome commented on docs/FAQs.md
> +	The error occurs with accessing the Makefile for the nokogiri gem. This occurs when initially installing the UWNerdist bundle. To explain it more clearly here is an explination from Stack overflow;
No need to indent anything as it's markdown.

2017-08-15 21:06 UTC, arumoy-shome commented on docs/FAQs.md
> +	gem uninstall #
these steps should be in a code block.

2017-08-15 21:06 UTC, arumoy-shome commented on docs/FAQs.md
> +	gem uninstall #
don't use `#` as a placeholder, it will be interpreted as a header by the markdown engine.

2017-10-06 17:14 UTC, arumoy-shome commented
@vishalbabu this PR has been stale for a while, any updates on this?

2017-10-08 14:55 UTC, vishalbabu commented
@arumoy-shome I just did an update on the repo and my FAQ.md doc is not on under the docs folder anymore. Think this issue can be closed for now.

2017-10-12 12:59 UTC, arumoy-shome commented
Huh that's weird, are you on your local branch? You won't see the file if you are on `master` since we didn't merge your PR yet.

2017-11-14 03:45 UTC, closed without merging